@echo off
set MATLAB=C:\Program Files\MATLAB\R2017a
"%MATLAB%\bin\win64\gmake" -f SOC_Modelling.mk  ISPROTECTINGMODEL=NOTPROTECTING RSIM_SOLVER_SELECTION=2 OPTS="-DSLMSG_ALLOW_SYSTEM_ALLOC -DTGTCONN -DON_TARGET_WAIT_FOR_START=0"
